use super::*;

mod root_authority;
use root_authority::*;

#[cfg(unix)]
#[test]
fn generated_web_checks_keep_app_local_yarn_lock_authoritative() {
    use std::ffi::OsString;
    use std::os::unix::fs::PermissionsExt;

    let _guard = lock_env();
    let temp = tempdir().unwrap();
    let template = materialize_template_worktree();
    let repo = temp.path().join("app-local-yarn");

    run_init(InitOpts {
        path: repo.clone(),
        scaffold: ScaffoldOpts::default(),
        template: Some(template.path().display().to_string()),
        template_mode: None,
        vcs_ref: None,
        force: false,
        defaults: true,
        no_input: true,
        no_vault: true,
        answers: AnswerOpts {
            repo_name: Some("app-local-yarn".into()),
            sqlx_enabled: Some(false),
            web_package_manager: Some("yarn".into()),
            frontend_apps: vec![FrontendApp {
                name: "web".into(),
                dir: "apps/web".into(),
                coverage_threshold: 80,
                kind: "vite".into(),
                role: "spa".into(),
            }],
            ..AnswerOpts::default()
        },
    })
    .unwrap();

    fs::create_dir_all(repo.join("apps/web")).unwrap();
    fs::write(
        repo.join("package.json"),
        r#"{"private":true,"packageManager":"yarn@1.22.22"}"#,
    )
    .unwrap();
    fs::write(
        repo.join("apps/package.json"),
        r#"{"private":true,"packageManager":"yarn@1.22.20"}"#,
    )
    .unwrap();
    fs::write(
        repo.join("apps/web/package.json"),
        r#"{"name":"web","scripts":{"lint":"true"},"installConfig":{"pnp":true}}"#,
    )
    .unwrap();
    fs::write(
        repo.join("apps/web/yarn.lock"),
        "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n",
    )
    .unwrap();
    fs::write(repo.join("apps/web/.node-version"), "20.19.1\n").unwrap();

    let fake_bin = repo.join("fake-bin");
    fs::create_dir_all(&fake_bin).unwrap();
    let fake_node = fake_bin.join("node");
    fs::write(
        &fake_node,
        r#"#!/bin/sh
if [ "${1:-}" = "-" ] && [ "${2:-}" = "--jig-process-probe" ]; then
  if kill -0 "$3" 2>/dev/null; then printf '%s\n' live; else printf '%s\n' stale; fi
  exit 0
fi
if [ "${1:-}" = "-" ] && [ "${2:-}" = "--jig-yarn-lockfile-kind" ]; then
  lockfile="${3:-}"
  [ -n "$lockfile" ] && [ -f "$lockfile" ] && [ ! -L "$lockfile" ] || exit 1
  if tr -d '\r' < "$lockfile" | grep -Eq '^# yarn lockfile v1$'; then
    printf '%s\n' classic
  else
    printf '%s\n' berry
  fi
  exit 0
fi
if [ "${1:-}" = "-" ] && [ "${2:-}" = "--jig-yarn-authority-preflight" ]; then
  exit 0
fi
if [ "${1:-}" = "-" ] && [ "${2:-}" = "--jig-yarn-classic-config" ]; then
  printf '%s\n' 'classic:dGVzdA=='
  exit 0
fi
if [ "${1:-}" = "-" ] && [ "${2:-}" = "--jig-yarn-classic-pnp-proof" ]; then
  [ -s "$4" ] || exit 1
  cksum "$4" | awk '{print $1}'
  exit 0
fi
if [ "${1:-}" = "-" ] && [ "${2:-}" = "--jig-workspace-metadata" ]; then
  [ "${3:-}" != "contains" ]
  exit $?
fi
if [ "${1:-}" = "-" ] && [ "${2:-}" = "--jig-yarn-classic-manifest" ]; then
  manifest="$3"
  if tr '\n' ' ' < "$manifest" | grep -Eq '"installConfig"[[:space:]]*:[[:space:]]*\{[^}]*"pnp"[[:space:]]*:[[:space:]]*true'; then
    printf '%s\n' true
    exit 0
  fi
  exit 1
fi
if [ "${1:-}" = "-" ] && [ "${2:-}" = "--jig-yarn-berry-config" ]; then
  linker=pnp
  if [ -f .yarnrc.yml ] && grep -Eq '^[[:space:]]*nodeLinker[[:space:]]*:[[:space:]]*(node-modules|pnpm)' .yarnrc.yml; then
    linker=node-modules
  fi
  config="{\"nodeLinker\":\"$linker\",\"cacheFolder\":\"$(pwd)/.yarn/cache\",\"installStatePath\":\"$(pwd)/.yarn/install-state.gz\",\"pnpUnpluggedFolder\":\"$(pwd)/.yarn/unplugged\",\"pnpEnableInlining\":false,\"pnpEnableEsmLoader\":false}"
  printf '%s' "$config" | base64 | tr -d '\n'
  printf '\n'
  exit 0
fi
if [ "${1:-}" = "-" ] && [ "${2:-}" = "--jig-yarn-config-value" ]; then
  config="$(printf '%s' "$3" | base64 --decode 2>/dev/null || printf '%s' "$3" | base64 -D)"
  case "$4" in
    nodeLinker) printf '%s\n' "$config" | sed -n 's/.*"nodeLinker":"\([^"]*\)".*/\1/p' ;;
    *) exit 1 ;;
  esac
  exit 0
fi
if [ "${1:-}" = "-" ] && [ "${2:-}" = "--jig-yarn-pnp-proof" ]; then
  scope="$3"
  for required in "$4" "$scope/.pnp.data.json" "$scope/.yarn/install-state.gz" "$scope/.yarn/cache/dependency.zip"; do
    [ -s "$required" ] && [ ! -L "$required" ] || exit 1
    cksum "$required"
  done | cksum | awk '{print $1}'
  exit 0
fi
if [ "${1:-}" = "-" ] && [ "${2:-}" = "--jig-node-modules-proof" ]; then
  root="$3/node_modules"
  entries="$(find "$root" -mindepth 1 \( -type f -o -type l \) ! -name '.jig-web-dependencies-v3' ! -name '.jig-web-dependencies-v3.tmp.*' ! -path "$root/.cache/*" ! -path "$root/.vite/*" ! -path "$root/.tmp/*" ! -name '.DS_Store' -print | LC_ALL=C sort)"
  [ -n "$entries" ] || exit 1
  printf '%s\n' "$entries" | while IFS= read -r entry; do
    relative="${entry#"$root"/}"
    if [ -L "$entry" ]; then
      printf 'link %s %s\n' "$relative" "$(readlink "$entry")"
    else
      printf 'file %s %s\n' "$relative" "$(wc -c < "$entry" | tr -d ' ')"
      [ "${entry##*/}" != "package.json" ] || cksum "$entry"
    fi
  done | cksum | awk '{print $1}'
  exit 0
fi
if [ "${1:-}" = "-" ]; then
  shift
  for file in "$@"; do
    if [ -f "$file" ]; then cksum "$file"; fi
    if [ -d "$file" ]; then
      find "$file" -type f -print | LC_ALL=C sort | while IFS= read -r nested; do
        printf '%s\n' "$nested"
        cksum "$nested"
      done
    fi
  done | cksum | awk '{print $1}'
fi
exit 0
"#,
    )
    .unwrap();
    fs::set_permissions(&fake_node, fs::Permissions::from_mode(0o755)).unwrap();

    let fake_yarn = fake_bin.join("yarn");
    fs::write(
        &fake_yarn,
        r#"#!/bin/sh
set -eu
case "${1:-}" in
  --version)
    printf '%s\n' '1.22.22'
    ;;
  config)
    [ "${2:-}" = "--json" ] || exit 2
    current="$PWD"
    linker=pnp
    while [ "$current" != "${current%/*}" ]; do
      if [ -f "$current/.yarnrc.yml" ] && grep -Eq '^[[:space:]]*nodeLinker[[:space:]]*:' "$current/.yarnrc.yml"; then
        linker="$(sed -n 's/^[[:space:]]*nodeLinker[[:space:]]*:[[:space:]]*\([^[:space:]#]*\).*/\1/p' "$current/.yarnrc.yml" | tail -1)"
        break
      fi
      current="${current%/*}"
    done
    printf '%s\n' "{\"key\":\"nodeLinker\",\"effective\":\"$linker\"}"
    printf '%s\n' "{\"key\":\"cacheFolder\",\"effective\":\"$PWD/.yarn/cache\"}"
    printf '%s\n' "{\"key\":\"installStatePath\",\"effective\":\"$PWD/.yarn/install-state.gz\"}"
    printf '%s\n' "{\"key\":\"pnpUnpluggedFolder\",\"effective\":\"$PWD/.yarn/unplugged\"}"
    printf '%s\n' '{"key":"pnpEnableInlining","effective":true}'
    printf '%s\n' '{"key":"pnpEnableEsmLoader","effective":false}'
    ;;
  install)
    count=0
    if [ -f "$INSTALL_COUNT" ]; then count="$(cat "$INSTALL_COUNT")"; fi
    count=$((count + 1))
    printf '%s\n' "$count" > "$INSTALL_COUNT"
    pwd > "$INSTALL_CWD"
    if [ "${FAIL_INSTALL:-0}" = "1" ]; then exit 9; fi
    printf '%s\n' 'generated classic pnp loader' > .pnp.js
    ;;
  run) ;;
  *) exit 2 ;;
esac
"#,
    )
    .unwrap();
    fs::set_permissions(&fake_yarn, fs::Permissions::from_mode(0o755)).unwrap();

    let install_count = repo.join("install-count");
    let install_cwd = repo.join("install-cwd");
    let mut path = OsString::from(fake_bin.as_os_str());
    path.push(":");
    path.push(std::env::var_os("PATH").unwrap_or_default());
    let resolve_spec = || {
        let output = std::process::Command::new("bash")
            .args([
                "scripts/check-webapps.sh",
                "package-manager-spec",
                "apps/web",
            ])
            .current_dir(&repo)
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "nested Yarn spec resolution failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        String::from_utf8(output.stdout).unwrap().trim().to_owned()
    };
    let run_mode = |mode: &str, fail_install: bool| {
        let output = std::process::Command::new("bash")
            .args(["scripts/check-webapps.sh", mode])
            .current_dir(&repo)
            .env("PATH", &path)
            .env("INSTALL_COUNT", &install_count)
            .env("INSTALL_CWD", &install_cwd)
            .env("FAIL_INSTALL", if fail_install { "1" } else { "0" })
            .output()
            .unwrap();
        assert_eq!(
            output.status.success(),
            !fail_install,
            "app-local Yarn web {mode} failed:\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    };

    let node_version_file = std::process::Command::new("bash")
        .args(["scripts/check-webapps.sh", "node-version-file", "apps/web"])
        .current_dir(&repo)
        .output()
        .unwrap();
    assert!(
        node_version_file.status.success(),
        "app-local Node version resolution failed: {}",
        String::from_utf8_lossy(&node_version_file.stderr)
    );
    assert_eq!(
        String::from_utf8_lossy(&node_version_file.stdout).trim(),
        "apps/web/.node-version"
    );
    let workflow = fs::read_to_string(repo.join(".github/workflows/webapp-checks.yml")).unwrap();
    assert!(workflow.contains("node-version-file: ${{ steps.node-version.outputs.path }}"));
    assert_eq!(resolve_spec(), "yarn@1.22.20");

    run_mode("bootstrap", false);
    assert_eq!(
        fs::read_to_string(&install_cwd).unwrap().trim(),
        fs::canonicalize(repo.join("apps/web"))
            .unwrap()
            .display()
            .to_string()
    );
    assert!(
        !repo.join("yarn.lock").exists(),
        "bootstrap replaced the adopted app-local dependency scope with a root lock"
    );
    assert!(repo.join("apps/web/.pnp.js").exists());

    run_mode("lint", false);
    assert_eq!(fs::read_to_string(&install_count).unwrap().trim(), "1");

    fs::write(
        repo.join("package.json"),
        r#"{"private":true,"packageManager":"yarn@1.22.19"}"#,
    )
    .unwrap();
    assert_eq!(resolve_spec(), "yarn@1.22.20");
    run_mode("lint", true);
    assert_eq!(fs::read_to_string(&install_count).unwrap().trim(), "2");
    run_mode("lint", false);
    assert_eq!(fs::read_to_string(&install_count).unwrap().trim(), "3");

    fs::write(
        repo.join("apps/package.json"),
        r#"{"private":true,"packageManager":"yarn@1.22.18"}"#,
    )
    .unwrap();
    assert_eq!(resolve_spec(), "yarn@1.22.18");
    run_mode("lint", false);
    assert_eq!(fs::read_to_string(&install_count).unwrap().trim(), "4");

    fs::create_dir_all(repo.join("apps/.yarn/releases")).unwrap();
    fs::write(repo.join("apps/.yarn/releases/yarn.cjs"), "runtime-v1\n").unwrap();
    run_mode("lint", false);
    assert_eq!(fs::read_to_string(&install_count).unwrap().trim(), "5");
    fs::write(repo.join("apps/.yarn/releases/yarn.cjs"), "runtime-v2\n").unwrap();
    run_mode("lint", false);
    assert_eq!(fs::read_to_string(&install_count).unwrap().trim(), "6");
}

#[test]
fn generated_root_yarn_receipt_tracks_nested_app_authority_and_runtime_assets() {
    use std::ffi::OsString;
    use std::os::unix::fs::PermissionsExt;

    let _guard = lock_env();
    let temp = tempdir().unwrap();
    let template = materialize_template_worktree();
    let repo = temp.path().join("root-yarn-nested-authority");
    let app_dir = "apps/group/web";

    run_init(InitOpts {
        path: repo.clone(),
        scaffold: ScaffoldOpts::default(),
        template: Some(template.path().display().to_string()),
        template_mode: None,
        vcs_ref: None,
        force: false,
        defaults: true,
        no_input: true,
        no_vault: true,
        answers: AnswerOpts {
            repo_name: Some("root-yarn-nested-authority".into()),
            sqlx_enabled: Some(false),
            web_package_manager: Some("yarn".into()),
            frontend_apps: vec![FrontendApp {
                name: "web".into(),
                dir: app_dir.into(),
                coverage_threshold: 80,
                kind: "vite".into(),
                role: "spa".into(),
            }],
            ..AnswerOpts::default()
        },
    })
    .unwrap();

    fs::create_dir_all(repo.join(app_dir)).unwrap();
    fs::write(
        repo.join("package.json"),
        r#"{"private":true,"packageManager":"yarn@4.18.0","workspaces":["apps/group/*"]}"#,
    )
    .unwrap();
    fs::write(repo.join("yarn.lock"), "__metadata:\n  version: 8\n").unwrap();
    fs::write(repo.join(".yarnrc.yml"), "nodeLinker: node-modules\n").unwrap();
    fs::write(
        repo.join("apps/group/package.json"),
        r#"{"private":true,"packageManager":"yarn@3.8.7"}"#,
    )
    .unwrap();
    fs::write(
        repo.join(app_dir).join("package.json"),
        r#"{"name":"web","private":true,"scripts":{"lint":"true"},"dependencies":{"dependency":"1.0.0"}}"#,
    )
    .unwrap();

    let fake_bin = repo.join("fake-bin");
    fs::create_dir_all(&fake_bin).unwrap();
    let fake_yarn = fake_bin.join("yarn");
    fs::write(
        &fake_yarn,
        r#"#!/bin/sh
set -eu
case "$PWD" in
  */apps/group/*)
    if [ -n "${YARN_EXECUTION_MARKER:-}" ] && [ -L "${SYMLINKED_YARN_AUTHORITY:-}" ]; then
      : > "$YARN_EXECUTION_MARKER"
    fi
    if [ -n "${YARN_PATH_PROBE:-}" ] && [ -f "$YARN_PATH_PROBE" ]; then
      "$YARN_PATH_PROBE"
    fi
    ;;
esac
case "${1:-}" in
  --version)
    case "$PWD" in
      */apps/group/web) printf '%s\n' '3.8.7' ;;
      *) printf '%s\n' '4.17.1' ;;
    esac
    ;;
  config)
    [ "${2:-}" = "--json" ] || exit 2
    printf '%s\n' '{"key":"nodeLinker","effective":"node-modules"}'
    printf '{"key":"cacheFolder","effective":"%s/.yarn/cache"}\n' "$PWD"
    printf '{"key":"installStatePath","effective":"%s/.yarn/install-state.gz"}\n' "$PWD"
    printf '{"key":"pnpUnpluggedFolder","effective":"%s/.yarn/unplugged"}\n' "$PWD"
    printf '%s\n' '{"key":"pnpEnableInlining","effective":true}'
    printf '%s\n' '{"key":"pnpEnableEsmLoader","effective":false}'
    ;;
  install)
    count=0
    if [ -f "$INSTALL_COUNT" ]; then count="$(cat "$INSTALL_COUNT")"; fi
    printf '%s\n' "$((count + 1))" > "$INSTALL_COUNT"
    mkdir -p node_modules/dependency
    printf '%s\n' '{"name":"dependency","version":"1.0.0"}' > node_modules/dependency/package.json
    ;;
  run) ;;
  *) exit 2 ;;
esac
"#,
    )
    .unwrap();
    fs::set_permissions(&fake_yarn, fs::Permissions::from_mode(0o755)).unwrap();

    let install_count = repo.join("install-count");
    let yarn_execution_marker = repo.join("unexpected-yarn-execution");
    let symlinked_yarn_authority = repo.join("apps/group/.yarn");
    let yarn_path_probe = repo.join("tools/yarn.cjs");
    let mut path = OsString::from(fake_bin.as_os_str());
    path.push(":");
    path.push(std::env::var_os("PATH").unwrap_or_default());
    let harness = RootYarnHarness {
        repo,
        app_dir,
        path,
        install_count,
        yarn_execution_marker,
        symlinked_yarn_authority,
        yarn_path_probe,
    };

    assert_nested_yarn_authority_changes(&harness);
    assert_external_yarn_runtime_authorities_are_rejected(&harness, temp.path());
    assert_yarn_authority_producer_failures(&harness);
    assert_symlinked_yarn_authorities_are_rejected(&harness, temp.path());
}

#[cfg(unix)]
#[test]
fn generated_web_checks_preserve_and_override_inherited_yarn_berry_linker() {
    use std::ffi::OsString;
    use std::os::unix::fs::PermissionsExt;

    let _guard = lock_env();
    let temp = tempdir().unwrap();
    let template = materialize_template_worktree();
    let repo = temp.path().join("yarn-linker-inheritance");
    run_init(InitOpts {
        path: repo.clone(),
        scaffold: ScaffoldOpts::default(),
        template: Some(template.path().display().to_string()),
        template_mode: None,
        vcs_ref: None,
        force: false,
        defaults: true,
        no_input: true,
        no_vault: true,
        answers: AnswerOpts {
            repo_name: Some("yarn-linker-inheritance".into()),
            sqlx_enabled: Some(false),
            web_package_manager: Some("yarn".into()),
            frontend_apps: vec![FrontendApp {
                name: "web".into(),
                dir: "apps/web".into(),
                coverage_threshold: 80,
                kind: "vite".into(),
                role: "spa".into(),
            }],
            ..AnswerOpts::default()
        },
    })
    .unwrap();

    fs::create_dir_all(repo.join("apps/web")).unwrap();
    fs::write(
        repo.join("package.json"),
        r#"{"private":true,"packageManager":"yarn@4.18.0","workspaces":["tools/*"]}"#,
    )
    .unwrap();
    fs::write(repo.join(".yarnrc.yml"), "nodeLinker: node-modules\n").unwrap();
    fs::write(
        repo.join("apps/web/package.json"),
        r#"{"name":"web","private":true,"packageManager":"yarn@4.18.0"}"#,
    )
    .unwrap();
    fs::write(
        repo.join("apps/web/yarn.lock"),
        "__metadata:\n  version: 8\n",
    )
    .unwrap();
    fs::write(
        repo.join("apps/web/.yarnrc.yml"),
        "checksumBehavior: reset\n",
    )
    .unwrap();

    let fake_bin = repo.join("fake-bin");
    fs::create_dir_all(&fake_bin).unwrap();
    let fake_yarn = fake_bin.join("yarn");
    fs::write(
        &fake_yarn,
r#"#!/bin/sh
set -eu
case "${1:-}" in
  --version)
    printf '%s\n' '4.17.1'
    ;;
  config)
    [ "${2:-}" = "--json" ] || exit 2
    current="$PWD"
    linker=pnp
    while [ "$current" != "${current%/*}" ]; do
      if [ -f "$current/.yarnrc.yml" ] && grep -Eq '^[[:space:]]*nodeLinker[[:space:]]*:' "$current/.yarnrc.yml"; then
        linker="$(sed -n 's/^[[:space:]]*nodeLinker[[:space:]]*:[[:space:]]*\([^[:space:]#]*\).*/\1/p' "$current/.yarnrc.yml" | tail -1)"
        break
      fi
      current="${current%/*}"
    done
    printf '%s\n' "{\"key\":\"nodeLinker\",\"effective\":\"$linker\"}"
    printf '%s\n' "{\"key\":\"cacheFolder\",\"effective\":\"$PWD/.yarn/cache\"}"
    printf '%s\n' "{\"key\":\"installStatePath\",\"effective\":\"$PWD/.yarn/install-state.gz\"}"
    printf '%s\n' "{\"key\":\"pnpUnpluggedFolder\",\"effective\":\"$PWD/.yarn/unplugged\"}"
    printf '%s\n' '{"key":"pnpEnableInlining","effective":true}'
    printf '%s\n' '{"key":"pnpEnableEsmLoader","effective":false}'
    ;;
  install)
    if grep -Eq '^[[:space:]]*nodeLinker[[:space:]]*:[[:space:]]*pnp' .yarnrc.yml; then
      if [ -d node_modules ]; then rm -rf node_modules; fi
      printf '%s\n' 'const RAW_RUNTIME_STATE = '\''{"packageRegistryData":[]}'\'';' > .pnp.cjs
      mkdir -p .yarn
      printf '%s\n' state > .yarn/install-state.gz
    else
      rm -f .pnp.cjs .pnp.js
      mkdir -p node_modules/test-package
      printf '%s\n' '{"name":"test-package"}' > node_modules/test-package/package.json
    fi
    ;;
  run) ;;
  *) exit 2 ;;
esac
"#,
    )
    .unwrap();
    fs::set_permissions(&fake_yarn, fs::Permissions::from_mode(0o755)).unwrap();
    let mut path = OsString::from(fake_bin.as_os_str());
    path.push(":");
    path.push(std::env::var_os("PATH").unwrap_or_default());
    let command = |mode: &str| {
        let mut command = std::process::Command::new("bash");
        command.args(["scripts/check-webapps.sh", mode]);
        if mode == "dependencies-ready" {
            command.arg("apps/web");
        }
        command
            .current_dir(&repo)
            .env("PATH", &path)
            .output()
            .unwrap()
    };

    let inherited = command("bootstrap");
    assert!(
        inherited.status.success(),
        "inherited Yarn linker bootstrap failed: {}",
        String::from_utf8_lossy(&inherited.stderr)
    );
    assert!(repo.join("apps/web/node_modules").is_dir());
    assert!(command("dependencies-ready").status.success());

    fs::write(
        repo.join("apps/web/.yarnrc.yml"),
        "nodeLinker: pnp\nchecksumBehavior: reset\n",
    )
    .unwrap();
    assert!(!command("dependencies-ready").status.success());
    let overridden = command("bootstrap");
    assert!(
        overridden.status.success(),
        "app Yarn linker override failed: {}",
        String::from_utf8_lossy(&overridden.stderr)
    );
    assert!(repo.join("apps/web/.pnp.cjs").is_file());
    assert!(command("dependencies-ready").status.success());
}

#[cfg(unix)]
#[test]
fn generated_yarn_berry_accepts_historical_inline_loader_formats() {
    use std::ffi::OsString;
    use std::os::unix::fs::PermissionsExt;

    let _guard = lock_env();
    let temp = tempdir().unwrap();
    let template = materialize_template_worktree();

    for (format, loader) in [("object", ".pnp.js"), ("json-string", ".pnp.cjs")] {
        let repo = temp.path().join(format!("yarn-berry-{format}"));
        run_init(InitOpts {
            path: repo.clone(),
            scaffold: ScaffoldOpts::default(),
            template: Some(template.path().display().to_string()),
            template_mode: None,
            vcs_ref: None,
            force: false,
            defaults: true,
            no_input: true,
            no_vault: true,
            answers: AnswerOpts {
                repo_name: Some(format!("yarn-berry-{format}")),
                sqlx_enabled: Some(false),
                web_package_manager: Some("yarn".into()),
                frontend_apps: vec![FrontendApp {
                    name: "web".into(),
                    dir: "apps/web".into(),
                    coverage_threshold: 80,
                    kind: "vite".into(),
                    role: "spa".into(),
                }],
                ..AnswerOpts::default()
            },
        })
        .unwrap();

        let app = repo.join("apps/web");
        fs::create_dir_all(&app).unwrap();
        fs::write(
            app.join("package.json"),
            r#"{"name":"web","private":true,"packageManager":"yarn@2.4.3","dependencies":{"dependency":"1.0.0"}}"#,
        )
        .unwrap();
        fs::write(app.join("yarn.lock"), "__metadata:\n  version: 4\n").unwrap();

        let fake_bin = repo.join("fake-bin");
        fs::create_dir_all(&fake_bin).unwrap();
        let fake_yarn = fake_bin.join("yarn");
        fs::write(
            &fake_yarn,
            r#"#!/bin/sh
set -eu
case "${1:-}" in
  --version)
    printf '%s\n' '2.4.3'
    ;;
  config)
    [ "${2:-}" = "--json" ] || exit 2
    printf '%s\n' '{"key":"nodeLinker","effective":"pnp"}'
    printf '%s\n' "{\"key\":\"cacheFolder\",\"effective\":\"$PWD/.yarn/cache\"}"
    printf '%s\n' "{\"key\":\"installStatePath\",\"effective\":\"$PWD/.yarn/install-state.gz\"}"
    printf '%s\n' "{\"key\":\"pnpUnpluggedFolder\",\"effective\":\"$PWD/.yarn/unplugged\"}"
    printf '%s\n' '{"key":"pnpEnableInlining","effective":true}'
    if [ "${TEST_ESM:-0}" = "1" ]; then
      printf '%s\n' '{"key":"pnpEnableEsmLoader","effective":true}'
    fi
    ;;
  install)
    mkdir -p .yarn/cache
    printf '%s\n' archive > .yarn/cache/dependency.zip
    printf '%s\n' state > .yarn/install-state.gz
    if [ "${TEST_ESM:-0}" = "1" ]; then
      printf '%s\n' esm-loader > .pnp.loader.mjs
    else
      rm -f .pnp.loader.mjs
    fi
    if [ "$TEST_FORMAT" = object ]; then
      rm -f .pnp.cjs
      {
        printf '%s\n' 'function $$SETUP_STATE(hydrateRuntimeState, basePath) {'
        printf '%s\n' '  return hydrateRuntimeState({'
        printf '%s\n' '    "packageRegistryData": [[null, [[null, {'
        printf '%s\n' '      "packageLocation": "./.yarn/cache/dependency.zip/node_modules/dependency/"'
        printf '%s\n' '    }]]]]'
        printf '%s\n' '  }, {basePath: basePath || __dirname});'
        printf '%s\n' '}'
      } > .pnp.js
    else
      rm -f .pnp.js
      printf '%s\n' 'function $$SETUP_STATE(hydrateRuntimeState, basePath) {' > .pnp.cjs
      printf '%s\n' '  return hydrateRuntimeState(JSON.parse('\''{"packageRegistryData":[[null,[[null,{"packageLocation":"./.yarn/cache/dependency.zip/node_modules/dependency/"}]]]]}'\''), {basePath: basePath || __dirname});' >> .pnp.cjs
      printf '%s\n' '}' >> .pnp.cjs
    fi
    ;;
  run) ;;
  *) exit 2 ;;
esac
"#,
        )
        .unwrap();
        fs::set_permissions(&fake_yarn, fs::Permissions::from_mode(0o755)).unwrap();
        let mut path = OsString::from(fake_bin.as_os_str());
        path.push(":");
        path.push(std::env::var_os("PATH").unwrap_or_default());
        let command = |mode: &str, esm: bool| {
            std::process::Command::new("bash")
                .args(["scripts/check-webapps.sh", mode, "apps/web"])
                .current_dir(&repo)
                .env("PATH", &path)
                .env("TEST_FORMAT", format)
                .env("TEST_ESM", if esm { "1" } else { "0" })
                .output()
                .unwrap()
        };

        let installed = command("dependencies-install", false);
        assert!(
            installed.status.success(),
            "{format} install failed: {}",
            String::from_utf8_lossy(&installed.stderr)
        );
        assert!(app.join(loader).is_file());
        assert!(command("dependencies-ready", false).status.success());

        fs::rename(
            app.join(".yarn/cache/dependency.zip"),
            app.join(".yarn/cache/dependency.zip.missing"),
        )
        .unwrap();
        assert!(!command("dependencies-ready", false).status.success());
        fs::rename(
            app.join(".yarn/cache/dependency.zip.missing"),
            app.join(".yarn/cache/dependency.zip"),
        )
        .unwrap();
        fs::write(app.join(".yarn/cache/unrelated.zip"), "unrelated\n").unwrap();
        assert!(command("dependencies-ready", false).status.success());

        let loader_path = app.join(loader);
        let loader_length = fs::metadata(&loader_path).unwrap().len();
        let oversized_loader = fs::OpenOptions::new()
            .write(true)
            .open(&loader_path)
            .unwrap();
        oversized_loader.set_len(64 * 1024 * 1024 + 1).unwrap();
        drop(oversized_loader);
        assert!(
            !command("dependencies-ready", false).status.success(),
            "{format} accepted an oversized parsed loader"
        );
        let restored_loader = fs::OpenOptions::new()
            .write(true)
            .open(&loader_path)
            .unwrap();
        restored_loader.set_len(loader_length).unwrap();
        drop(restored_loader);
        assert!(command("dependencies-ready", false).status.success());

        if format == "object" {
            assert!(!command("dependencies-ready", true).status.success());
            assert!(command("dependencies-install", true).status.success());
            assert!(command("dependencies-ready", true).status.success());
            fs::write(app.join(".pnp.loader.mjs"), "changed\n").unwrap();
            assert!(
                !command("dependencies-ready", true).status.success(),
                "an explicit pnpEnableEsmLoader=true did not attest the ESM loader"
            );
        }
    }
}

#[cfg(unix)]
#[test]
fn generated_yarn_classic_stamps_actual_artifacts_and_proves_referenced_packages() {
    use std::ffi::OsString;
    use std::os::unix::fs::PermissionsExt;

    let _guard = lock_env();
    let temp = tempdir().unwrap();
    let template = materialize_template_worktree();
    let repo = temp.path().join("yarn-classic-artifacts");
    run_init(InitOpts {
        path: repo.clone(),
        scaffold: ScaffoldOpts::default(),
        template: Some(template.path().display().to_string()),
        template_mode: None,
        vcs_ref: None,
        force: false,
        defaults: true,
        no_input: true,
        no_vault: true,
        answers: AnswerOpts {
            repo_name: Some("yarn-classic-artifacts".into()),
            sqlx_enabled: Some(false),
            web_package_manager: Some("yarn".into()),
            frontend_apps: vec![FrontendApp {
                name: "web".into(),
                dir: "apps/web".into(),
                coverage_threshold: 80,
                kind: "vite".into(),
                role: "spa".into(),
            }],
            ..AnswerOpts::default()
        },
    })
    .unwrap();

    fs::create_dir_all(repo.join("apps/web")).unwrap();
    fs::write(repo.join("package.json"), r#"{"private":true}"#).unwrap();
    let app_manifest = repo.join("apps/web/package.json");
    fs::write(
        &app_manifest,
        r#"{"name":"web","private":true,"packageManager":"yarn@1.22.22","workspaces":["packages/*"],"dependencies":{"dependency":"1.0.0","workspace":"1.0.0"},"installConfig":{"pnp":true}}"#,
    )
    .unwrap();
    fs::write(repo.join("apps/web/yarn.lock"), "# yarn lockfile v1\n").unwrap();
    let app = repo.join("apps/web");
    fs::write(app.join(".node-version"), "24.19.0\n").unwrap();
    fs::create_dir_all(app.join("packages/workspace")).unwrap();
    fs::write(
        app.join("packages/workspace/package.json"),
        r#"{"name":"workspace","version":"1.0.0"}"#,
    )
    .unwrap();
    fs::write(app.join("packages/workspace/source.js"), "source-v1\n").unwrap();

    let cache = repo.join("classic-cache");

    let fake_bin = repo.join("fake-bin");
    fs::create_dir_all(&fake_bin).unwrap();
    let fake_yarn = fake_bin.join("yarn");
    fs::write(
        &fake_yarn,
        r#"#!/bin/sh
set -eu
case "${1:-}" in
  --version)
    printf '%s\n' '1.22.22'
    ;;
  cache)
    [ "${2:-}" = "dir" ] || exit 2
    printf '%s/v6\n' "$TEST_CACHE"
    ;;
  config)
    [ "${2:-}" = "list" ] && [ "${3:-}" = "--json" ] || exit 2
    printf '%s\n' '{"type":"info","data":"yarn config"}'
    printf '%s\n' "{\"type\":\"inspect\",\"data\":{\"--pnp\":true,\"cache-folder\":\"$TEST_CACHE\"}}"
    ;;
  install)
    mkdir -p "$TEST_CACHE/v6/dependency/node_modules/dependency"
    printf '%s\n' '{"name":"dependency","version":"1.0.0"}' > "$TEST_CACHE/v6/dependency/node_modules/dependency/package.json"
    if [ "${TEST_PNP:-0}" = "1" ]; then
      rm -rf node_modules
      {
        printf '%s\n' 'const path = require("path");'
        printf '%s\n' 'let packageInformationStores = new Map(['
        printf '%s\n' '  ["dependency", new Map([["1.0.0", {'
        printf '    packageLocation: path.resolve(__dirname, "%s/v6/dependency/node_modules/dependency/"),\n' "$TEST_CACHE"
        printf '%s\n' '  }]])],'
        printf '%s\n' '  ["workspace", new Map([["1.0.0", {'
        printf '%s\n' '    packageLocation: path.resolve(__dirname, "./packages/workspace/"),'
        printf '%s\n' '  }]])],'
        printf '%s\n' '  [null, new Map([[null, {'
        printf '%s\n' '    packageLocation: path.resolve(__dirname, "./"),'
        printf '%s\n' '  }]])],'
        printf '%s\n' ']);'
        printf '%s\n' 'let locatorsByLocations = new Map(['
        printf '%s\n' ']);'
      } > .pnp.js
    else
      rm -f .pnp.js .pnp.cjs
      mkdir -p node_modules/dependency
      printf '%s\n' '{"name":"dependency"}' > node_modules/dependency/package.json
    fi
    ;;
  run) ;;
  *) exit 2 ;;
esac
"#,
    )
    .unwrap();
    fs::set_permissions(&fake_yarn, fs::Permissions::from_mode(0o755)).unwrap();
    let mut path = OsString::from(fake_bin.as_os_str());
    path.push(":");
    path.push(std::env::var_os("PATH").unwrap_or_default());
    let command = |mode: &str, pnp: bool, override_value: Option<&str>| {
        let mut command = std::process::Command::new("bash");
        command
            .args(["scripts/check-webapps.sh", mode, "apps/web"])
            .current_dir(&repo)
            .env("PATH", &path)
            .env("TEST_PNP", if pnp { "1" } else { "0" })
            .env("TEST_CACHE", &cache);
        if let Some(value) = override_value {
            command.env("YARN_PLUGNPLAY_OVERRIDE", value);
        }
        command.output().unwrap()
    };
    let assert_success = |output: std::process::Output, label: &str| {
        assert!(
            output.status.success(),
            "{label} failed:\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    };

    assert_success(
        command("dependencies-install", true, None),
        "Classic PnP artifact install",
    );
    assert_success(
        command("dependencies-ready", true, None),
        "Classic PnP artifact readiness",
    );

    fs::write(app.join("packages/workspace/source.js"), "source-v2\n").unwrap();
    assert_success(
        command("dependencies-ready", true, None),
        "workspace source edit should not invalidate dependencies",
    );

    fs::write(app.join(".yarnrc"), "--pnp false\n").unwrap();
    assert!(
        !command("dependencies-ready", true, None).status.success(),
        "a Classic RC change did not invalidate readiness"
    );
    assert_success(
        command("dependencies-install", true, None),
        "actual PnP artifact after RC change",
    );
    assert!(
        !command("dependencies-ready", true, Some("0"))
            .status
            .success()
    );
    assert_success(
        command("dependencies-install", true, Some("0")),
        "actual PnP artifact with override change",
    );

    let workspace_manifest = app.join("packages/workspace/package.json");
    let workspace_manifest_contents = fs::read_to_string(&workspace_manifest).unwrap();
    fs::remove_file(&workspace_manifest).unwrap();
    assert!(
        !command("dependencies-ready", true, Some("0"))
            .status
            .success(),
        "a missing referenced workspace manifest did not invalidate readiness"
    );
    fs::write(&workspace_manifest, workspace_manifest_contents).unwrap();
    assert_success(
        command("dependencies-ready", true, Some("0")),
        "restored workspace manifest",
    );

    let cache_package = cache.join("v6/dependency");
    let missing_cache_package = cache.join("v6/dependency.missing");
    fs::rename(&cache_package, &missing_cache_package).unwrap();
    assert!(
        !command("dependencies-ready", true, Some("0"))
            .status
            .success(),
        "a missing referenced Classic cache package did not invalidate readiness"
    );
    fs::rename(&missing_cache_package, &cache_package).unwrap();
    fs::create_dir_all(cache.join("v6/unrelated/node_modules/unrelated")).unwrap();
    fs::write(
        cache.join("v6/unrelated/node_modules/unrelated/package.json"),
        "{}\n",
    )
    .unwrap();
    assert_success(
        command("dependencies-ready", true, Some("0")),
        "unrelated Classic cache addition",
    );
}
