/// Repository-level files that can change frontend dependency resolution,
/// contract generation, or the shared check runner independently of an app's
/// own source tree.
pub(super) const FRONTEND_SHARED_INPUTS: &[&str] = &[
    "package.json",
    "**/package.json",
    "**/package.json5",
    "**/package.yaml",
    "**/*.patch",
    "**/*.diff",
    ".node-version",
    ".npmrc",
    "**/.node-version",
    "**/.npmrc",
    ".pnpmfile.cjs",
    "pnpmfile.cjs",
    ".yarnrc",
    ".yarnrc.yml",
    ".yarn/**",
    "**/.yarnrc",
    "**/.yarnrc.yml",
    "**/.yarn/**",
    ".pnp.cjs",
    ".pnp.data.json",
    ".pnp.js",
    ".pnp.loader.mjs",
    "patches/**",
    "bunfig.toml",
    "bun.lock",
    "bun.lockb",
    "npm-shrinkwrap.json",
    "package-lock.json",
    "pnpm-lock.yaml",
    "pnpm-workspace.yaml",
    "yarn.lock",
    "scripts/check-webapps.sh",
    "scripts/check-webapp-scripts.mjs",
    "scripts/contracts.mjs",
    "scripts/enforce-coverage.cjs",
    "scripts/web-node.cjs",
    "eslint.config.shared.mjs",
    "openapi/**",
    "packages/*-api-client/**",
];
